# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         OpenOffice-OODoc
version:      1.106
version_from: OODoc.pm
installdirs:  site
requires:
    Archive::Zip:                  1.05
    XML::XPath:                    1.13

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
