# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         OpenOffice-OODoc
version:      1.307
version_from: OODoc.pm
installdirs:  site
requires:
    Archive::Zip:                  1.06
    File::Temp:                    0.12
    Time::Local:                   1.07
    XML::Twig:                     3.15

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
