#!/usr/bin/perl -w

=head1	NAME

export_images - Exporting all the images included in a document

=head1	SYNOPSIS

Very short program exporting images found in an OpenOffice.org document.

With only one argument (filename), every image is exported. The second
(optional) argument is a filter, to select only images whose name match
the given string.

In this example, only the content of the document is used; images belonging
to any page header or footer are ignored. If you replace 'content' by
'styles' in the code below, you will get the header/footer images and not
the content ones.

See the ref man for a more sophisticated use of the 'exportImages' method.



Usage : export_images <filename> [<filter>]

=cut

use OpenOffice::OODoc;

ooImage(file => $ARGV[0], member => 'content')
	->exportImages(name => $ARGV[1]);
exit;
